### ISSUE TITLE
job locking mechanism for certain tools

### ISSUE THREAD

**Issue by avilella** [veidenberg/pline#4]
Is there a flag to make sure that only one concurrent job can be executed for a certain tool in a running Pline server?
It is so successful on our end, some jobs trip over each other when different people kick them off, due to the nature of the job.

**Comment by veidenberg** [comment]
You mean disabling the start of another job until the previous one has finished? Currently there is no flag for that.
Multiple instances of a tool shouldn't cause problems since Pline runs each job independently in its own working directory with input/output files. You can also launch multiple Pline servers with separate data directories (set in `server_settings.cfg`). I hope it helps.

**Comment by avilella** [comment]
Gotcha, that's a good way of solving it. For the tasks that have this type of constraint on my side, I can devise a job locking mechanism in the task itself, and print the status of the waiting tasks in the STDERR instead. Thanks for clarifying.

**Comment by veidenberg** [comment]
Also, you can chain multiple steps of the same tool in a Pline pipeline (click "add a step" in the Pline UI, and you can reuse the pipeline with import/export button). When you run the pipeline, Pline will wait for each step (job run) to finish before starting the next one.
