### ISSUE TITLE
STDERR verbosity of the task window expanded by default

### ISSUE THREAD

**Issue by avilella** [veidenberg/pline#5]
While one of the Pline tasks is running, I can see the last line of the prompt being shown. If I click on the single-line prompt of the running task, the window expands and shows me everything printed in the prompt (STDERR/STDOUT), sometimes going beyond the bottom of the browser window.

Is there a way to set the height of the prompt window for a specific task? E.g. if we want the task window to show the 10 latest lines of the prompt, or 500 pixels, is there a way to set that up? Thanks.

**Comment by veidenberg** [comment]
I fixed the log line interface container height in the latest commit to the github repository.
You can change the current `max-height` CSS property value in [index.html](https://github.com/veidenberg/pline/blob/fb8fa4b5afb31d4bd5ab085414b82d838ff63ba3/index.html#L171). The example website is a minimal Pline integration demo (that's why it has silly things like animated emoji status messages - you can edit/remove these in `index.html`). A better Pline container can be by built by following the [documentation](http://wasabiapp.org/pline/guide/) and an advanced  integration example like the [Wasabi webapp](http://was.bi).
